parameters:
  includeSlowTests: false

steps:
- checkout: none

- script: /root/scripts/azure-build.sh nightly
  condition: eq('${{ parameters.includeSlowTests }}', 'true')
- script: /root/scripts/azure-build.sh
  condition: eq('${{ parameters.includeSlowTests }}', 'false')

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: "build_archive"
    targetPath: ./build/
