steps:
- task: DownloadPipelineArtifact@0
  inputs:
    artifactName: "build_archive"
    targetPath: .

- script: /root/scripts/azure-test.sh

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: "JUnit"
    testResultsFiles: "build/results/*.tests.xml"
    mergeTestResults: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "cobertura"
    summaryFileLocation: "build/results/*.coverage.xml"
