name: $(BuildDefinitionName)-$(SourceBranchName)-$(Rev:.rr)-$(BuildID)
trigger:
 - master
pr: none

jobs:
- job: Build
  pool:
    vmImage: ubuntu-16.04
  container:
    image: angr/ci:2
  steps:
  - template: ./steps/linux-build.yml

- job: Lint
  pool:
    vmImage: ubuntu-16.04
  container:
    image: angr/ci:2
  dependsOn: Build
  condition: succeeded()
  steps:
  - template: ./steps/linux-lint.yml

- job: Test
  pool:
    vmImage: ubuntu-16.04
  container:
    image: angr/ci:2
    options: --cap-add=SYS_PTRACE
  dependsOn: Build
  condition: succeeded()
  variables:
    NUM_WORKERS: 10
  strategy:
    maxParallel: 10
    matrix:
      worker_0:
        WORKER: 0
      worker_1:
        WORKER: 1
      worker_2:
        WORKER: 2
      worker_3:
        WORKER: 3
      worker_4:
        WORKER: 4
      worker_5:
        WORKER: 5
      worker_6:
        WORKER: 6
      worker_7:
        WORKER: 7
      worker_8:
        WORKER: 8
      worker_9:
        WORKER: 9
  steps:
  - template: ./steps/linux-test.yml
